kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
- rollout.yaml
- svc.yaml
- post-analysistemp.yaml

namePrefix: kustomizer-
