kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
- rollout-transform.yaml

resources:
- rollout.yaml
- svc.yaml
- post-analysistemp.yaml

namePrefix: kustomizer-

vars:
- name: ROLLOUT_NAME
  objref:
    kind: Rollout
    name: rollout-bg
    apiVersion: argoproj.io/v1alpha1
  fieldRef:
    fieldpath: metadata.name
