kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: post-bg-analysis
spec:
  metrics:
  - name: analysis
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleeper
                image: alpine:3.8
                command: [sh,-c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 1

