apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bg
  namespace: argo-rollouts
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bg
  template:
    metadata:
      labels:
        app: rollout-bg
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.17.0
          ports:
          - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kinda-worker2
  strategy:
    blueGreen:
      #autoPromotionEnabled: true
      activeService: kustomizer-rollout-active-service
      postPromotionAnalysis:
        templates:
        - templateName: kustomizer-post-bg-analysis
