apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bg
  namespace: argo-rollouts
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bg
  template:
    metadata:
      labels:
        app: rollout-bg
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.17.0
          ports:
          - containerPort: 80
        - name: ubuntu
          image: ubuntu:21.04
          command: echo $(ROLLOUT_NAME)
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kinda-worker2
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: master
                operator: In
                values:
                - admin
            topologyKey: kubernetes.io/hostname

  strategy:
    blueGreen:
      #autoPromotionEnabled: true
      activeService: kustomizer-rollout-active-service
      postPromotionAnalysis:
        templates:
        - templateName: kustomizer-post-bg-analysis
